name: 'Local Testnet'
description: 'Run local testnet with configurable OP Geth and Publisher branches'
author: 'Compose Network'

inputs:
  op-geth-branch:
    description: 'OP Geth branch name'
    required: true
  publisher-branch:
    description: 'Publisher branch name'
    required: true
  local-testnet-image-tag:
    description: 'Local testnet Docker image tag'
    required: false
    default: 'latest'
  pr-number:
    description: 'Pull request number (for status updates)'
    required: false
    default: '0'
  pr-sha:
    description: 'Pull request commit SHA (for status updates)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API access'
    required: true
  l1-chain-id:
    description: 'L1 chain ID'
    required: true
  l1-cl-url:
    description: 'L1 consensus layer URL'
    required: true
  l1-el-url:
    description: 'L1 execution layer URL'
    required: true
  wallet-address:
    description: 'Wallet address'
    required: true
  wallet-private-key:
    description: 'Wallet private key'
    required: true
  coordinator-private-key:
    description: 'Coordinator private key'
    required: true
  verifier-wallet:
    description: 'Verifier wallet address'
    required: true
  verifier-key:
    description: 'Verifier key'
    required: true

outputs:
  test-result:
    description: 'Test result (success or failure)'
    value: ${{ steps.smoke-tests.outcome }}

runs:
  using: 'composite'
  steps:
    - name: Set status to pending
      if: inputs.pr-sha != ''
      shell: bash
      run: |
        curl -s -X POST \
          -H "Authorization: token ${{ inputs.github-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.pr-sha }}" \
          -d '{
            "state": "pending",
            "description": "Local testnet tests are running...",
            "context": "Local Testnet CI",
            "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

    - name: Set up Docker Buildx
      shell: bash
      run: |
        # Check if docker buildx is available
        if ! docker buildx version &> /dev/null; then
          echo "Setting up Docker Buildx..."
          docker buildx create --use --name builder --driver docker-container || true
          docker buildx inspect builder --bootstrap
        else
          echo "Docker Buildx already available"
        fi

    - name: Run local testnet
      shell: bash
      run: |
        set -e  # Exit immediately if any command fails
        PWD=`pwd`
        docker run --rm \
           --add-host=host.docker.internal:host-gateway \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v ${PWD}:/workspace \
           -w /workspace \
           -e HOST_PROJECT_PATH=${PWD} \
           ghcr.io/compose-network/local-testnet:${{ inputs.local-testnet-image-tag }} l2 \
             --l1-chain-id ${{ inputs.l1-chain-id }} \
             --l1-cl-url=${{ inputs.l1-cl-url }} \
             --l1-el-url=${{ inputs.l1-el-url }} \
             --wallet-address=${{ inputs.wallet-address }} \
             --wallet-private-key=${{ inputs.wallet-private-key }} \
             --coordinator-private-key=${{ inputs.coordinator-private-key }} \
             --genesis-balance-wei=10000000000000000000 \
             --compose-network-name=hoodi \
             --dispute-network-name=hoodi \
             --dispute-owner-address=${{ inputs.wallet-address }} \
             --dispute-proposer-address=${{ inputs.wallet-address }} \
             --dispute-guardian-address=${{ inputs.wallet-address }} \
             --dispute-verifier-address=${{ inputs.verifier-wallet }} \
             --dispute-aggregation-vkey=${{ inputs.verifier-key }} \
             --compose-contracts-url=https://github.com/compose-network/contracts.git \
             --compose-contracts-branch=develop \
             --publisher-url=https://github.com/compose-network/publisher.git \
             --publisher-branch=${{ inputs.publisher-branch }} \
             --op-geth-url=https://github.com/compose-network/op-geth.git \
             --op-geth-branch=${{ inputs.op-geth-branch }}

    - name: Set up Go
      shell: bash
      run: |
        # Check if Go is already installed and at the correct version
        if command -v go &> /dev/null; then
          CURRENT_GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
          echo "Go is already installed: $CURRENT_GO_VERSION"
          if [[ "$CURRENT_GO_VERSION" == "1.25.0" ]]; then
            echo "Correct Go version already installed"
            exit 0
          fi
        fi

        # Download and install Go 1.25.0
        echo "Installing Go 1.25.0..."
        curl -s -L -O https://go.dev/dl/go1.25.0.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go1.25.0.linux-amd64.tar.gz
        rm go1.25.0.linux-amd64.tar.gz

        # Add to PATH
        echo "/usr/local/go/bin" >> "$GITHUB_PATH"
        export PATH="/usr/local/go/bin:$PATH"

        # Verify installation
        go version

    - name: Checkout dome test repository
      shell: bash
      run: |
        # Clone the dome repository
        echo "Cloning compose-network/dome repository..."
        git clone --depth 1 https://github.com/compose-network/dome.git dome
        cd dome
        echo "Repository cloned successfully"
        git log -1 --oneline

    - name: Parse test pattern from Makefile
      id: parse-tests
      shell: bash
      working-directory: dome
      run: |
        # Extract the test pattern from the smoke-test target in the Makefile
        TEST_PATTERN=$(grep -A 5 '^smoke-test:' Makefile | grep -o '\-test\.run="[^"]*"' | sed 's/-test\.run="\(.*\)"/\1/')
        echo "pattern=$TEST_PATTERN" >> "$GITHUB_OUTPUT"
        echo "Extracted test pattern: $TEST_PATTERN"

    - name: Run smoke tests
      id: smoke-tests
      continue-on-error: true
      shell: bash
      working-directory: dome
      run: |
        cp ../output.yaml configs/config.yaml
        mkdir -p bin && go test -c ./test/ -o bin/dome
        echo "Running smoke tests with INFO log level..."
        echo "Test pattern from Makefile: ${{ steps.parse-tests.outputs.pattern }}"
        LOG_LEVEL=INFO bin/dome -test.v -test.count=1 -test.run="${{ steps.parse-tests.outputs.pattern }}" 2>&1 | tee test-output.log
        exit ${PIPESTATUS[0]}

    - name: Parse test results and post comment
      if: always() && steps.smoke-tests.outcome != 'skipped' && inputs.pr-number != '0'
      shell: bash
      working-directory: dome
      run: |
        # Parse test results from the log file
        if [ -f test-output.log ]; then
          echo "## Test Results" > test-summary.md
          echo "" >> test-summary.md

          # Extract test results
          grep -E "^(--- PASS:|--- FAIL:)" test-output.log | while read -r line; do
            if echo "$line" | grep -q "PASS:"; then
              test_name=$(echo "$line" | sed 's/--- PASS: \(.*\) (.*/\1/')
              echo "🟢 **$test_name** - PASS" >> test-summary.md
            elif echo "$line" | grep -q "FAIL:"; then
              test_name=$(echo "$line" | sed 's/--- FAIL: \(.*\) (.*/\1/')
              echo "🔴 **$test_name** - FAIL" >> test-summary.md
            fi
          done

          # Add workflow run link
          echo "" >> test-summary.md
          echo "---" >> test-summary.md
          echo "📊 [View full test logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) - look for the 'Run smoke tests' step of the workflow." >> test-summary.md

          # Post comment to PR
          # Escape the content for JSON by replacing special characters
          COMMENT_BODY=$(sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/g' test-summary.md | tr -d '\n' | sed 's/\\n$//')
          curl -s -X POST \
            -H "Authorization: token ${{ inputs.github-token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr-number }}/comments" \
            -d "{\"body\": \"$COMMENT_BODY\"}"
        else
          echo "No test output file found"
        fi

    - name: Set status to success
      if: steps.smoke-tests.outcome == 'success' && inputs.pr-sha != ''
      shell: bash
      run: |
        curl -s -X POST \
          -H "Authorization: token ${{ inputs.github-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.pr-sha }}" \
          -d '{
            "state": "success",
            "description": "Local testnet tests passed!",
            "context": "Local Testnet CI",
            "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

    - name: Set status to failure
      if: (steps.smoke-tests.outcome == 'failure' || failure()) && inputs.pr-sha != ''
      shell: bash
      run: |
        curl -s -X POST \
          -H "Authorization: token ${{ inputs.github-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.pr-sha }}" \
          -d '{
            "state": "failure",
            "description": "Local testnet tests failed",
            "context": "Local Testnet CI",
            "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
