name: Manual Testnet Run

on:
  workflow_dispatch:
    inputs:
      op-geth-branch:
        description: 'OP Geth branch'
        required: true
        default: 'stage'
      publisher-branch:
        description: 'Publisher branch'
        required: true
        default: 'develop'
      image-tag:
        description: 'Local testnet image tag'
        required: false
        default: 'latest'

jobs:
  run-testnet:
    runs-on: public-isolated
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local testnet
        uses: compose-network/github-actions/actions/local-testnet@main
        with:
          # Repository configuration
          op-geth-branch: ${{ inputs.op-geth-branch }}
          publisher-branch: ${{ inputs.publisher-branch }}
          local-testnet-image-tag: ${{ inputs.image-tag }}

          # GitHub token
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # L1 configuration
          l1-chain-id: ${{ secrets.LOCAL_TESTNET_L1_CHAIN_ID }}
          l1-cl-url: ${{ secrets.LOCAL_TESTNET_L1_CL }}
          l1-el-url: ${{ secrets.LOCAL_TESTNET_L1_EL }}

          # Wallet configuration
          wallet-address: ${{ secrets.LOCAL_TESTNET_WALLET_ADDRESS }}
          wallet-private-key: ${{ secrets.LOCAL_TESTNET_WALLET_PK }}
          coordinator-private-key: ${{ secrets.LOCAL_TESTNET_COORDINATOR_PK }}

          # Verifier configuration
          verifier-wallet: ${{ secrets.LOCAL_TESTNET_VERIFIER_WALLET }}
          verifier-key: ${{ secrets.LOCAL_TESTNET_VERIFIER_PK }}
